<br><br>
<div style="page-break-before:always;">
<div class="crsLarge" style="text-align:center;">Auditory Left-Brain Learners</div>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The best way for auditory left-brain learners to learn is by hearing the new material presented in the form of language, either words or numbers, in a detailed, step-by-step way. They also think by speaking their thoughts aloud and conversing aloud with others. They work well with accurate data, facts, figures, and statistics and make excellent researchers, often backing up their lectures and presentations with information that supports their topic and gets their ideas across. 
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;They are sensitive to the quality of other people's speech, noticing mistakes in dialogue, such as grammatical and syntactical errors, poor usage of words, repetitive phrases, and poor delivery. They become uncomfortable when speakers drone on or use repetitive language, inappropriate pauses, or too many "ums." Being conscious of speech, they are careful to be good speakers themselves and make great orators. They plan out and rehearse what they are going to say, making sure their sentences are grammatically correct and their language is precise and clear, with appropriate word choices. Many are conscious of timing and phrasing, pausing at the right place for added effect and modulating their voices in a way to keep their audiences engaged. They also make good editors, not for finding visual errors in spelling, but for being conscious of how the text should sound when read aloud. They enjoy collecting words and relish putting them together in interesting ways. They like fancy words, such as cogitate for think, and words that sound good and provide the closest shade of meaning. 
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;They are great conversationalists, and enjoy talking to a wide range of people. Their great auditory recall manifests itself in their speech when they quote other people like an automatic verbal playback system, replaying conversations almost word-for-word. They can be the life of the party with their storehouse of humorous anecdotes, interesting tidbits from current events and history, the wit and wisdom they heard from others, and their excellent verbal presentation skills. They can relate famous quotations, jokes, riddles, tales, poetry, and lines from the classics, movies, or lectures almost verbatim. They need constant auditory stimuli. 
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;They cannot handle absolute silence. If it is too quiet they feel uncomfortable, and will provide the auditory stimuli themselves by humming, singing, whistling, talking aloud, turning on a radio talk show, television, or audiotape lecture, or calling someone on the telephone. In an office or classroom, when it is too quiet, the auditory people will start talking, wanting to discuss everything. They will either ask many questions or talk to people nearby. If no one will respond to them they may just start talking to themselves aloud. The only time they need silence is when they are studying or reading, because music, noise, or the talking of others distracts them from "hearing" their own thoughts. 
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Even though they do not maintain steady eye contact with a speaker, because when listening, people's eyes tend to move left and right in the direction of their ears, they are good listeners and will ask a speaker many questions. Although their discussions can become lengthy because they speak with so much sequential, analytical detail, their questions make others feel understood and appreciated. 
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Because auditory left-brain people think by speaking aloud, some have a tendency to repeat what people around them say, either in their own way or a better one. This may be annoying to others, but auditory left-brain people are not doing this to be rude; they only repeat what others say to think about it more clearly. They also .seem to make a running commentary on everything that is happening around them and may sound to others as if they are criticizing or analyzing everything. They are not trying to be critical-they just speak all their thoughts aloud when other people would keep their thoughts to themselves. Auditory left-brain people may need to understand this tendency, lest they unintentionally turn other people off. 
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;They work sequentially and will keep their files and papers orderly. Some enjoy the sequential aspect of working with mathematics by doing number and logic puzzles and solving math problems in everyday life. Some understand the highly mathematical and sequential processes involved in economics, stocks, taxes, and finances and enjoy reading financial papers and business journals, keeping up with the stock market and the business world. They like to keep their financial records, both personal and business, straight, and like to be organized at tax time to do their returns. 
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Left-brain auditory people who are musically inclined enjoy listening to music and going to concerts, theater, or musicals. Reading music is a left-brain task because it involves converting musical sounds into symbols and vice versa. When they listen to music they are conscious of the technical aspects and analyze it according to their own high standards, judging its technical execution such as the arrangement or a singer's voice quality, which makes them excellent music critics. 
<br><br>
<div style="text-align:center;"><b>Accelerated Learning</b></div>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Auditory left-brain people can accelerate their learning by listening and talking. In the classroom, or in seminars, they learn through lectures, oral presentations, and discussion. They recall details of conversations, lists, chores, words to a song, or anything else if it is told to them in a step-by-step way. When learning how to fix a car, program a computer, or playa sport, they learn better by listening to directions than by watching someone else perform the task. When memorizing material for a test, they need to hear the material, talk about it, reread it aloud, or tape themselves reading aloud and then play it back several times. 
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;They grasp the meaning of verbal communication quickly without having to convert it into pictures. They can closely follow college lecture, a verbal training session on the job, or auditory directions, while others of different learning styles may be saying, "What did the speaker say? I don't get it." Auditory left- brain people usually find others clustering around them asking them to explain announcements given over a P.A. system or to repeat the new policies that the boss explained at a meeting. 
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;This group can be found attending lectures and seminars, or taking the audiotape or guided tours through museums. Some are so absorbed in listening to a lecture during a sightseeing trip that they forget to look at the sights! 
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Auditory media such as CD's, tape recorders, audio books, computers, movies, videos, radio, and television are good learning tools for them. They may relax by listening to news or talk shows on the radio while driving, or watching the evening news or a television documentary after work. They also enjoy reading books, news magazines, newspapers, and professional journals because as they read they hear the words in their head. Audio computer programs, verbal presentations, or texts presented in a step-by-step way are the best learning tools for them. 
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;They can learn well from technical manuals and instructional guides if they read them aloud. They are also good at writing them. These are the people who know how to program a computer or a VCR. If you do not already have an auditory left-brain friend you may want to search for one, because these are the people who understand the way things work in this technological age, based on the language of words, numbers, and computer terminology carried out in a logical, step-by-step way. 
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Many enjoy history, current events, and biographies because these are sequential, chronological, and verbal genres. 
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;They are sensitive to auditory distractions. When they are listening to a speaker, they become annoyed if anything distracts them. A passing car, a humming heater, or someone crunching chips will drive them out of their minds. Since they cannot tune out distractions as visual people can, they carefully orchestrate their listening environment to hear only the speaker or only their own thoughts. They have a hard time concentrating or studying with background music and need quiet to read and study. Head- phones may help them concentrate when there is too much auditory distraction. 
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Many auditory enjoy debate. They work well in teams and cooperative groups that involve discussion, and use this continual feedback to restructure and regroup their own thoughts.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;To comprehend better, they need to read aloud, read softly to themselves, or hear words in their mind. They need to stop frequently and ask themselves questions about what they read. They also need to hear what they read in a step-by-step way to grasp the material. If they read material that jumps from one idea to another without any order, they need to restructure it in their minds by asking questions in order to convert it into a step-by-step process and form an outline or study guide. They do not enjoy books that ramble on going nowhere, but those that are sequentially organized and move to a logical conclusion or resolution. 
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;In the workforce they can be found in jobs that require listening and talking in a step-by-step way. They may be public speakers, sales and marketing people, receptionists, lawyers, politicians, administrators, presenters, lecturers, college professors, teachers, disc jockeys, musicians, singers, songwriters, editors, writers, poets, actors and actresses, announcers, emcees, broadcasters, such as television news anchors, sportscasters, announcers in commercials, or audio book readers. Some become mathematicians, accountants, bookkeepers, bankers, financial planners, tax specialists, economists, and stockbrokers.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;No matter what their careers, auditory left-brain people are the workers asked to do tasks that involve speaking, listening, or giving oral presentations and training to the staff, clients, or trainees, because words and numbers are their medium for communication with the world. 
<br><br>
<div style="text-align:center;"><b>Adapting Learning to an Auditory Left-Brain Style</b></div>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Auditory left-brain people should ask an instructor to present material in an auditory, sequential way through lectures and discussion. Auditory left-brain people should use books on tape and should take their own notes in a linear manner. They should read the material aloud and into a tape recorder. They need to study with a partner or discussion group. 
</div>
