<br><br>
<div style="page-break-before:always;">
<div class="crsLarge" style="text-align:center;">Auditory Right-Brain Learners</div>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Auditory right-brain learners learn best through hearing and are attuned to sounds, music, rhythms, tones of voice, and strong sensory words that give an overview of the big picture. This group is sensitive to sounds that others miss. Musical harmony is important to them because they are particularly bothered by any dissonant sounds. They are attracted to beautiful sounds, sweet melodies, and pleasing voices and are repelled by annoying and grating sounds such as sirens, construction drills, or irritating voices.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;They enjoy traveling to get away from the dissonant sounds of a city to spend time relaxing amidst the sounds of nature in the mountains, a forest, or by the ocean. To keep the sounds at home or in their office pleasant, many have a good selection of tapes for background music. Some enjoy environmental sound tapes such as the sounds of the ocean, rain, birds in the forest, or running brooks.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;They have a good ear for music. They enjoy going to concerts, musicals, jazz brunches, music clubs, or religious and social ceremonies with musical services or presentations. While not adept at the language of words, they are like tape recorders when it comes to music. They can hear a tune, remember it exactly, and sing it or pick up an instrument and play it perfectly by ear. Many auditory right-brain people in the music field may not have had any formal music training and cannot read music; they just make music and it sounds great. They spend time practicing and creating their own songs and instrumentals. They may create a song, tune, or whole symphony in their heads and then reproduce it with instruments or by singing. It is as if they are tapped into an internal CD player that creates new melodies and songs.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Auditory right-brainers get creative ideas for sound effects, often coming up with new types of sounds, new genres of music, new instruments, or new combinations of instruments and sounds, such as the combination of music and the sounds of nature. These types of learners feel uncomfortable when there is no auditory stimulus. They will create it by turning on music or making auditory stimuli themselves, such as singing, humming, whistling, tapping a beat, making their mouth sound like instruments or sound effects, mimicking voices or people's accents, or doing impersonations or cartoon characters’ voices. Although they do not maintain direct eye contact with a speaker (because their eyes move side to side in the direction of their ears) they are acutely aware of nonverbal communication and tones of voice. They can pick up on someone's negativity, hidden anger, resentment, and sarcasm. Conversely, they can also pick up someone's sincerity and loving, caring, and kind attitude and will immediately respond to that person. Others may think they are mind readers because they can grasp people's true meaning from subtle nuances of tone in face-to-face and telephone conversations, no matter what words are used to hide the speaker's feelings. Auditory right-brain people appear to be deep, not saying much, but understanding all. They enjoy being with people who do not stress their verbal auditory system. Some like to talk a lot to friends about their interests and hobbies, usually getting to the point quickly, and changing topics frequently, while others like to be with people with whom they can relax, not have to talk much, and with whom they can communicate with few words or strong sensory language.
<br><br>
<div style="text-align:center;"><b>Accelerated Learning</b></div>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Auditory right-brain people can accelerate their learning by listening to sound, music, and strong sensory language that give an overview or big picture. They learn more from the sounds of words than from a printed text. When they are memorizing material for a test or speech, it is better for them to hear someone else read the material or write down the information themselves and read it aloud, talk about it, or tape-record it so they can play it back several times. They remember words better and can repeat them verbatim if they are combined with music, rhymes, rhythm, catchy songs and tunes, jingles in commercials and advertisements, poetry, raps, beats, environmental sounds, or by mimicking distinctive voice qualities or accents. They recall a story conveyed in a musical, or the words to a song on music videos. As children, they learned the alphabet by singing the alphabet song. Their best learning pathway is open when words and numbers are tied to music.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;This group, which is not attuned to symbolic, abstract language, does not learn well from lectures unless the speaker gets to the point and uses sensory words. They need to hear the whole concept and the bottom line. When other people's conversation becomes too abstract, detailed, and sequential, some auditory right-brain people may either cut them off and say, "I get it," because they have grasped the whole idea, or they tune out, drift off, and hum a song, tap a beat, or even sing while the other person is still speaking. They will refocus on the lecture only when the speaker gets to the point.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Live music, CD's and tapes, slide shows with music, movies, videos, television, computers, CD-ROM programs, and video games with good music and sound effects are the best learning materials for them. Imaginative, interactive computer programs that use sound effects, voices, and music are also good.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;They understand better when words are tied to movies, videos, and real-life demonstrations because of the right brain's excellent visual-spatial memory. They can remember learning material better by mentally converting words into a movie, with sound effects, imagined music, and dialogue being acted out. This association technique helps auditory right-brain people learn abstract subjects such as grammar, spelling, vocabulary, foreign languages, or algebra, traditionally taught in a left-brain way.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;To remember procedures, auditory right-brain people need to visualize each action and discuss it aloud, understanding the global overview first and then filling in the details. Their study partner should go over each step slowly and carefully with them, ask them to repeat the material back, and check their accuracy.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;When writing, speaking, or reading they tend to get to the point quickly and often leave out the unimportant, abstract words. They sometimes mix up words or letters. They may come up with a word other than the one they mean; for example, meaning to say "dog" but instead saying "cat" because of their close association. Also, they may read the first few letters of a word and intuitively try to figure out the rest of the word, thus coming out with a word that sounds close to the right one but is not correct. They get a global impression instead of reading each letter in order.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;When doing math, they understand broad concepts or processes but may not attend to the specific details of checking their work, doing step-by-step processes, or proving their answers. They can get an answer intuitively by finding relationships and patterns and grasping the whole process, but when it comes to the details of calculations, they may make errors. They may see a multiple-digit number simultaneously and come up with the first response that comes to mind. Thus, they may read 378 as 738 or 873. Others may think they have dyslexia, but they do not; it is just that their right brain reads everything simultaneously instead of in linear order.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Since language is usually located in the left hemisphere of the brain, auditory people with a right-brain preference may have poor listening skills and may not be able to follow spoken language quickly. They often need directions repeated several times in order to grasp them and will ask those around them, "What did the speaker say? What are the directions?" Since they mostly grasp words that carry sensory stimuli they may miss important abstract words such as not, if, after, before, and other prepositional phrases. Thus, if they hear "Do not read this," they may pick up only "Do read this," causing them to make mistakes in school or on the job. Auditory right-brain people need to learn coping strategies. Those who are speaking to them should also understand that auditory right-brain people need instructions to be given slowly, one item at a time, often repeated two or three times, with sensory imagery if possible. They need the extra milliseconds to access each word as an image in the right side of the brain and convert it back into words by processing language in the left side of the brain.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Because they are easily distracted by sounds, they need an environment in which only one auditory stimulus is going on at once, whether it is a speaker or music. Headphones are a good way for them to shut out unwanted sounds when they are learning.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Auditory right-brain learners think mostly intuitively, without words. They pick up meaning from music, sounds in the environment, and people's tones of voice. Left-brain people may marvel at how someone can think and learn without words, but it is a different kind of learning –- it is an instantaneous knowledge that does not require words, like two friends knowing what the other is thinking without even talking.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;To accelerate reading, right-brain auditory people first need an overview of the reading material. Then, as they read they can fit the details into the whole picture. They need to imagine the text as a movie with sound effects, accents and tones of voice, feelings, and music to make the material come alive. Vocabulary describing sound attracts their attention.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Auditory right-brain learners comprehend better when they read aloud, or if that is disruptive to others they should read softly, or hear the words in their head. Since they are better at grasping an overview of what they are reading, they tend to miss details that may affect the meaning. On comprehension tests they get the gist of what they read, but have difficulty with specific facts about time order, sequence, or questions about details.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;To overcome this right-brain tendency, they need auditory right-brain techniques to get them to slow down, pay attention, and read words from left to right, letter by letter, without skipping any words. By using pointers, guides, or highlighters as they read aloud they can monitor their progress. Visualization techniques help them experience what they are reading and can help them improve their retention of smaller details and abstract time words and prepositions. They can talk about what they are experiencing as they do this as an auditory reinforcement of their visualization.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;In the workforce, you may find auditory right-brain people in jobs that require listening to sounds, music, and nature in a global, simultaneous way. They may be musicians, songwriters, members of a rock group, jazz trio or quartet, rhythm and blues group, orchestra, or band. Auditory right-brain people are so sensitive to sound and its variations that they are the ones who make good sound mixers and editors for a recording studio, concert hall, or music, movie, or video production company. Some may become the sound effects or special effects technicians for a movie, CD-ROM software, television, or video production company. Whatever their profession, auditory right-brain learners are low-key, laid-back people who enjoy harmony, music, and the positive vibrations that flow from people around them.
<br><br>
<div style="text-align:center;"><b>Adapting Learning to an Auditory Right-Brain Style</b></div>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Auditory right-brain people can ask an instructor to enhance their lectures with short sensory language, music, or sound effects, along with images, mind maps, real-life objects, or demonstrations. Because many lectures are too fast-paced for them to follow while taking notes, they need to get a printed study guide, text, or tape recording so they can work at their own pace to convert the words into a mental movie, into drawings of the information with key words highlighted, or idea webs that show the main topic and the details. They need to participate in real-life situations or find materials that give an overview and use sensory words and visual aids that correspond to the subject, and work at their own pace converting it into a movie in their mind while talking about it.
</div>
