<br><br>
<div style="page-break-before:always;">
<div class="crsLarge" style="text-align:center;">Kinesthetic Right-Brain Learners</div>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Kinesthetic right-brain learners learn by moving their gross motor muscles in a creative, imaginative, free-flowing, and unstructured way. They do not think in terms of words, but get information intuitively.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;They become highly restless if forced to stay still or remain in one place too long. They will feel so constrained and physically stressed that they will start to move around anyway. Their need to keep moving and changing activities may make them look hyperactive to others. It is actually when they are denied movement that they look distracted. It is better to give them movement activities related to the learning task, such as learning games, exercises, or simulations. Then they will be able to concentrate as well as people of other styles do when working in their element. Unless given productive activities related to their work, they will kick or swing their legs under the table, drum on the tabletop, slouch, rock in their seats, or find excuses to get up, whether it is to get a snack or look out the window.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Not all kinesthetic right-brain people are athletes. There are many other activities that involve movement. For them, movement can be moving in their mind from one topic or project to another.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Kinesthetic right-brain people can think about several things simultaneously and can have many projects going on at once. They can keep each one straight in their minds without any difficulty. They work in an impulsive, quick way, wanting to see results immediately so they can move on to another activity. In the rush to complete a project, they may not worry about whether the parts were done to perfection. They see the whole picture, not the details.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;There are also times when they consider a job done just by having thought of it. Some kinesthetic right-brain people put the idea out, do some preliminary work, and move on to another project. It is up to the detail-oriented people around them to pick up the pieces and complete the tasks so they can then move on to create new inventions. They are a wealth of new ideas and discoveries, like a brainstorm session in motion, giving the world a seemingly endless supply of novel, unique ideas.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Being goal-oriented, kinesthetic right-brain people have the ability to get things done, handling many projects at once. They are not time-oriented, so they do not tend to stick to schedules, routines, or time constraints. They are go-with-the-flow people who will do what they feel like at the moment. They can keep work moving and be a wealth of creativity and imagination, although others have to be willing to accept their lack of consciousness of time. At work, as frequently as they arrive late, they may also become so absorbed in a task that they may stay overtime just to complete it.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A kinesthetic right-brain person needs a comfortable environment full of activity, with room to stretch out and move. Some will get up and leave if they are bored or in a restricted environment. Being outdoors is high on their list because there they can move freely.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Kinesthetic right-brain people enjoy being with other people when they can do something together that doesn't require a lot of talk. Watch them during a football game and you may hear grunts, moans, or cheers. They can communicate action without speaking and use their body and arms to dramatize or express what they want to describe. When they do talk, they use short action words and get to the point quickly.
<br><br>
<div style="text-align:center;"><b>Accelerated Learning</b></div>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Kinesthetic right-brain people can accelerate their learning by moving in an unstructured, imaginative, and free-flowing way. They need to use their bodies and muscles to learn. Thus, they can learn better while cycling on a stationary bike, memorizing material while jumping rope, performing experiments, or playing creative games.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Kinesthetic right-brain people, often adventuresome and daring, enjoy challenges. They do not require step-by-step, detailed instructions. This group just needs to jump in and "do it." They pick up the how-to information by intuition or gut feelings and learn by trial and error, exploration, and discovery. They fully grasp the overall patterns of any situation and know what to do. Their excellent visual-spatial relations, intuition, and quick reflexes enable them to look at a problem, instantly judge a situation, and move accordingly, without words or written directions, to find the solution.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;They are whole-to-part learners who need to see the big picture first and fill in the details later. For example, they will not give a detailed verbal account of a sports event –- they will give the highlights and the winning score: the bottom line. If they see a whole math problem with the answer and several examples, they can figure out how to solve similar problems.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;They listen better while in motion with their eyes focused down and away from the speaker. They remember more when they are in motion than when they are sitting still. When they are moving they can relax and concentrate.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Writing on a flip chart or an erasable board with large markers works better for them than writing while sitting. By involving their whole arm, legs, and body, they can put the activity into the kinesthetic realm. Making a mind map of material they need to know by using their whole arm to write provides more activity and helps them recall what they learned. They doodle not because of a tactile need to write but because it offers more movement than sitting still.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;They need active real-life experiences or simulations. For example, when learning about accounting they would prepare a budget for a real company or an imaginary one they created for this learning experience. If volunteers are needed for a demonstration, kinesthetic right-brain learners jump at the chance to get out of their seats and do something. If they are learning a dance they will remember it not by watching someone else do it, but by doing it themselves. They need to fully immerse themselves in the experience in an unstructured way. Many of them do not want long explanations; they want to figure something out for themselves. They need teachers who will take on the role of a coach, use only key action words, and guide them if they ask for help.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;If a situation does not permit the kinesthetic right-brain person to do an activity, their next resort is to watch activity on television, videos, or movies. To remember what they learn, they need to act out the material or visualize themselves dramatizing it as if a movie were playing in their head. When they visualize they need to feel movement in their muscles. Their body may move and sway as they go through the movements in their mind. When they receive directions to drive to a friend's house, they experience themselves turning the car right or left, or whipping along a curve in the road in their mind.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Good learning materials for a kinesthetic right-brain person are manipulatives, games, building materials, tools, sports equipment, balls, exercise bikes, large flip charts, erasable boards, large markers, computers with action games, percussion instruments, guitars or organs, rhythmic music, hands-on models, or real objects to move. They like unstructured, non-sequential, high-action, fast-moving video games and CD-ROM interactive programs. If a computer program is too slow or too structured, they become bored. They prefer moving a joystick or a mouse.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Competitions and challenges interest kinesthetic right-brain people, either in games or on the job. They may participate in contests that determine who can sell or produce the most. They are goal-oriented and enjoy the thrill of winning points for themselves or their team. Make a game of anything and they will learn it.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;When they are studying for a test, they remember what they did while learning. For them to concentrate, distractions caused by the movement of others have to be eliminated. Working in a study carrel, using a divider, or facing a wall can keep them from noticing the movement of others, but they have to be comfortable while studying. Being stretched out on the floor or couch gives their muscles freedom of movement. They can work and study with or without music. Because they do not listen to the words, it does not interfere with their reading. The rhythm or beat stimulates their muscles to move or dance in time to the music. Their stress is reduced and their attention and motivation increases.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;By working in cooperative groups, kinesthetic right-brain learners have an opportunity to move around more from group to group. They thrive on change and interact with different people to satisfy their need for action.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;To accelerate reading, kinesthetic right-brain people need to convert words into a movie in which they are part of the action. Imagining that they are directing a video and converting the book or script into scenes or describing the action that would appear on the screen will make a book come alive for them. Whatever they do not feel themselves doing –- or imagining they are doing –- as they read will be lost to them.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;They read for the main idea or big picture, skipping small details, and are impatient with too many words. Thus, they tend to miss comprehension questions that deal with details, time sequence, or abstract ideas. It is not that they cannot remember details, but they need kinesthetic right-brain techniques to master them.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Kinesthetic right-brain people prefer short or highly action-packed books or how-to books that help them perform better. Unlike their left-brain counterparts, they need diagrams, photographs, or illustrations. They do not like to read a book from cover to cover but tend to skip around, getting what they need from it. They may learn just by looking at the pictures, glancing at the captions, or flipping through the pages, catching stray sentences that may give them all they need to know about a topic. They have an intuitive sense that helps them find what they need.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Kinesthetic right-brain people need to know the end product before they start. Thus, they need to know the reason they are reading something. They will be motivated if they feel it will help them do something better. Watch them zip through a book if they feel it will help them be the top in their field, boost their sales, or get a promotion. Books with summaries or key points at the beginning or end of a chapter help them find what is important and relevant to them.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;In the workforce, they can be found in jobs that require movement and frequent change. They may not attend to details, but they will work quickly to get a job done rapidly. With this group, speed and completion takes priority over spending a great deal of time on detail, as long as the end product works. They can be involved in building, making, or fixing things such as cars, houses, boats, motorcycles, computers, appliances, machines, or furniture. They may do work that requires physical exertion such as construction, building bridges, or lifting boxes. Some work in jobs that require traveling, but with little talk. Long-distance driving, flying, chauffeuring, making deliveries, and trucking are good options for them if they are not constrained by time schedules. They may enjoy the adventure and risks involved in police work, fire fighting, or the armed forces. Many of them like to be self-employed so they do not have to follow someone else's schedule. They may run their own construction, painting, wallpapering, cleaning, moving, lawn maintenance, plumbing, electrical, or repair companies.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;As scientists, kinesthetic right-brain people enjoy inventing, doing research and laboratory work, experimenting in the fields of paleontology, anthropology, quantum physics, or chemistry. If they go into medicine, they may run their own practices so they can have the freedom to set their own hours or move from one patient to another in ten different rooms.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;They may be involved in dancing, gymnastics, track, skiing, skating, swimming, sailing, snorkeling, surfing, biking, gymnastics, rollerblading, karate, judo, horseback riding, or aerobics. They may play football, soccer, tennis, and basketball for fun, but may have a hard time adjusting to being on an organized professional team because of the rigors of the schedule, discipline, and routine involved in that lifestyle.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Kinesthetic right-brain writers write short action stories that get to the point or how-to books that give key points without much detail. If they are artists they like art that requires action –- huge canvasses or sculptures with strong movement of color and design. They tend to make quick, impressionistic drawings that give a general idea of what they are trying to say. If they are actors or actresses they may prefer to play action parts or be stunt people. If they are musicians they enjoy playing an instrument that allows them to move their bodies. Kinesthetic right-brain learners tend to be better at playing by ear than reading notes. They also tend to be imaginative and can come up with new tunes or forms of music.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Their imagination, new ideas, openness to change, and inventiveness make them an excellent resource. Their commitment to action makes them product-oriented and able to produce a large amount of work in a short amount of time. As they move, the world also moves forward in new directions.
<br><br>
<div style="text-align:center;"><b>Adapting Learning to a Kinesthetic Right-Brain Style</b></div>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Kinesthetic right-brain learners need to ask an instructor to provide the big picture or overview using short, sensory language and let them do kinesthetic activities in a global, creative, free-flowing way. Since it is hard for them to follow auditory presentations, they need to have a <i>written</i> copy of notes or readings, or take dictation of a lecture and convert each word into a mental movie in which they play a part; a drawing with key words or numbers written in colorful, artistic, and creative ways; mind maps in color that show the main topic, the details, and their interconnections; or kinesthetic projects. They may need to find corresponding pictures, movies, or activities in which they can participate in real-life demonstrations. Instead of taking notes while sitting down, they can make the activity kinesthetic by writing and drawing in large letters or figures while standing up at a flip chart or board. They can convert information into a mind map that gives the big picture of the subject they are learning.
</div>
