<br><br>
<div style="page-break-before:always;">
<div class="crsLarge" style="text-align:center;">Kinesthetic Left-Brain Learners</div>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Kinesthetic left-brain learners think in an organized, systematic way and learn through moving their large motor muscles. Because the language function is in the left side of the brain, they can verbalize movement activities in systematic, structured ways.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;They need to move a great deal and are restless when they have to stay in one place. If they are forced to stay in one seat too long they will begin to move or rock in the seat, kick their legs, or get out of the seat spontaneously. Others may be distracted by their movements. But if they are given an opportunity to use their body they will actually stick to a task with great concentration; it is when they are denied movement that they find some other outlet for their kinesthetic needs that may not be productive. They are going to move anyway, whether restricted or not, so at least the lessons should be structured in a way that includes movement as a positive part of their training.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;They like team sports, organized games, or exercises that have rules and are done in a step-by-step way. Many kinesthetic left-brain people are very coordinated and can time their movements to be in synch with others. They often excel in synchronized swimming, gymnastics, acrobatics, or choreographed dance.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Not all kinesthetic left-brain people are athletic and coordinated, but they still require sequential movement activities in other fields; whether they are developing real estate, designing a CD-ROM program, curing a disease, or exploring a new hobby. Movement for them can be just mentally moving from one topic or project to another. They are systematic and orderly and tend to stick to and complete a task before moving on.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;They need room to move around and comfortable sitting areas to stretch out and relax. If a place does not allow them to move about or has no action-oriented activity, kinesthetic left- brain people will feel uncomfortable and bored because there is nothing for them to do there. They enjoy talking with other people while they are jogging, exercising, or working with someone else.
<br><br>
<div style="text-align:center;"><b>Accelerated Learning</b></div>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Kinesthetic left-brain people can accelerate their learning using an organized, systematic, step-by-step approach that involves moving their bodies and muscles. They are language-oriented, so they can describe what they are doing and follow verbal systematic directions for movement activities. They should get on an exercise bike and read or study while pedaling, or walk around the room while memorizing the lines to a play. Learning games, simulations, role-play, and competitions are great ways for them to learn. Whatever movement they do, they prefer to use a formula, structure, or outline for their work.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;It may appear to others that kinesthetic people are not listening because they are constantly moving, and they process thought better when their eyes look down and away from a speaker, but they are most attentive when they are in motion. It is so stressful for them to sit still with their eyes on a speaker that they cannot concentrate on listening. Yet when they are moving about they are relaxed, comfortable, and attentive.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Hands-on materials and manipulatives are important to kinesthetic learners, but they benefit more from moving their entire bodies, not just their hands. The simple act of standing up helps them learn because it gets their leg, arm, and other muscles moving. They need to write with large markers or chalk on a flip chart or chalkboard while standing. Doing math problems or outlining a report on a flip chart helps them to think better. By writing in large letters on a chalkboard, they can involve their arm muscles and take the activity into the kinesthetic realm. Kinesthetic left-brain people doodle or draw because it may be the only movement they are permitted in a constrained working or learning situation. It offers them some movement of their arms and hands, which may not fully satisfy them, but it is better than sitting still.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;In whatever subject they learn, they need to learn by doing something in a sequential way. Just listening to lectures and verbal explanations is not enough for them to assimilate the material. They should volunteer to be a demonstrator instead of just watching the demonstration. If they hear action words in sequential order, they will physically understand the material. They need a coach who will actively work through the steps of a process. If they are learning about computer software, they have to be at a computer while going through each step. If they are learning about carpentry, they will need the tools and materials to build something for themselves. They will remember not what an instructor does, but what <i>they</i> do.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;When memorizing material for a test or examination, they recall what they did with the material. When they study, they need to act out or dramatize the material, either physically or mentally, so they can remember it. If the subject is math or science, they need to work out the problems or experiments in a step-by-step way in real-life applications; for example, by doing the math required for sending a spaceship to the moon, mixing chemicals to produce medicine, or writing a CD-ROM program. If circumstances do not allow a kinesthetic left-brain person to do an activity, their next best resort is to watch activity-movies, television, or videos. Another kinesthetic method is to visualize themselves moving. In this way they can experience action without distracting others.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Kinesthetic left-brain people thrive on achievement, winning, challenges, and discovery. Being goal-oriented, they enjoy the thrill of the game, and their motivation increases in a competitive environment. They like competing with themselves or against teams. Since the left side of the brain handles facts and figures, kinesthetic left-brainers tend to discuss game scores or keep records of achievement of others or themselves.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Kinesthetic left-brain people need manipulatives, organized games, building materials, sports equipment, science projects, large markers, and large pieces of paper, flip charts, erasable boards, computers, musical instruments, hands-on models, kits, or real objects to move. They like structured high-action computer programs, especially CD-ROMs. Moving a joystick or a mouse interests them more than just typing on a keyboard.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Kinesthetic left-brain people can read, work, or study with or without music. Moving or dancing to the rhythm and beat of music can stimulate them to work better. When their muscles are in motion stress is reduced, their attention and motivation increase, and they learn faster. Kinesthetic left-brain people enjoy playing musical instruments that engage the whole body. They can handle a systematic approach to learning an instrument and will attend to the technical aspects of playing, such as timing, rhythm, and reading music.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Working in cooperative groups or teams helps kinesthetic left-brain learners because they can move around from group to group. But they like to work from a plan or structured outline so they know each step of the process beforehand. Interaction with different people in different groups fulfills their need to be where the action is.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;To accelerate reading, kinesthetic left-brain people should get actively involved in the reading material, either by physically acting out the text or imagining themselves doing so. To engage their interest and remember what they read, they need to mentally convert the words into an action movie. They will forget whatever they do not imagine themselves doing as they read.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Kinesthetic left-brain people prefer to read action-packed books. They like to read about movement-oriented activities in a detailed, step-by-step, well-organized way if it can help them improve what they do. The left brain's ability to think in terms of language helps them understand verbal or written directions for action-oriented subjects. They enjoy how-to books that help them perform better if they are written in logical, sequential ways. Business people enjoy reading how-to suggestions for improving their businesses. Sports lovers enjoy books that help them perfect their techniques.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;They need a purpose and an action-oriented reason to be motivated to read. If they know their sales will increase if they read the training manual, they will be sure to read it. If they know they need to pass a driver's license examination, they will force themselves to read the manual.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;In the workforce, kinesthetic left-brain people can be found in jobs that require movement along with left-brain organization, putting what they do into words or giving detailed verbal directions to others. Jobs that require traveling, speaking, and being clear and organized in one's presentation are found in sales, marketing, district management, owning a self-employed business, teaching, and training. Kinesthetic left-brain people who go into the sciences may be involved in experiments, research and laboratory work, or medical fields, becoming doctors and nurses.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Since they excel at movement jobs that are related to being on time, a function of the left side of the brain, they may be pilots, train conductors, chauffeurs, truck drivers, delivery people, or postal workers. Work that involves the physical body and using details, measurements, and precision are construction, farming, engineering, roadwork, painting, wallpapering, plumbing, electrical work, cleaning, furniture crafting, and doing repair work. Jobs that require physically protecting other people and that use the left-brain attention to structure, organization, and rules are in areas such as the armed forces, the police force, fire department, or secret service.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Kinesthetic left-brainers may be involved in organized sports and games or may use their verbal abilities to become sportscasters or coaches and instructors in movement fields such as aerobics, exercise, or dance. They may write action stories, sports columns, reviews of movies, dance, or theatrical performances, or organized and structured how-to books. Their ability to visualize action on a screen or stage may make them good screenwriters and playwrights. As artists they are structured and systematic in their work and will portray detailed action in illustrations, cartoons, comic strips, or advertising. They may be directors of movies, plays, or dance groups. They may become actors and actresses, musicians, performers, or instructors of performing arts that require body movement.
<br><br>
<div style="text-align:center;"><b>Adapting Learning to a Kinesthetic Left-Brain Style</b></div>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Kinesthetic left-brain people should ask an instructor to let them do movement activities in a sequential way to learn the material. If instruction is presented as a lecture they need to ask for outlines or study guides, or make their own notes in sequential order on a board or paper so they can convert the words into action, a mental movie in which they have a part, or an outline written in large lettering. They can find sequential materials, either written or in an audio-visual format, that relate to the subject and help them convert the text into action.
</div>
