<br><br>
<div style="page-break-before:always;">
<div class="crsLarge" style="text-align:center">Right- And Left-Brain Mixed Preferences</div>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Some people have a right- and left-brain mixed preference, which means that they perform some functions with one side of the brain and other functions with the other side. When they use the side of the brain that matches the task, there is no problem. Mixed preference learners just need to be aware of their strengths and know how to apply them to the task.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Sometimes people with a mixed preference use one side of the brain, but not necessarily in a way that matches the task. Some people use the right side of the brain for tasks that are better performed by the left side, and vice versa. Thus, these people may find their performance is not always at its best. At worst, it creates confusion and makes learning a great struggle in certain situations. Because of the difficulties this may create, in the rest of this section we will focus on the situations in which one is not using his or her brain in the best or most appropriate manner for the task, and what can be done about it.
<br><br>
<div style="text-align:center;"><b>Using the Right Side of the Brain for Left-Brain Tasks</b></div>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Most academic subjects in schools have been based on tasks such as reading, writing, spelling, grammar, public speaking, foreign language, and certain math computation functions that have been traditionally taught in a left-brain way, requiring understanding abstract symbols such as numbers, letters, and words. People who use the right side of the brain when taught in this left-brain manner find that it does not work and end up struggling. One reason these subjects are taught in a left-brain manner is that many people who became teachers and college instructors were people who succeeded in the educational system and could function well in this left-brain environment. Thus, when they taught the upcoming generation, they tended to use the same techniques -- left-brain ones -- that helped them learn the material. All the subjects listed below can be taught in a right-brain manner so that right-brain people can be successful. Right-brain techniques are presented in the book "How To Learn Anything Quickly" by Ricki Linkman.
<br><br>
<b><i>Reading</b></i>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;People with right-brain preferences read differently than those who read with the left side of their brain. The right side of their brain recognizes visual images, words, and patterns they have seen before. Right-brain people learn to read through sight-word recognition or by repeating patterns, known as linguistics or phonemic patterns, in which you read <i>at</i>, <i>fat</i>, <i>cat</i>, <i>hat</i>, and so forth. They also respond to sensory words that invoke strong images processed in the right side of the brain. Thus, when they read they are going after the big picture, the main points, the strong visual images, actions, sounds, and feelings. There is nothing wrong with reading in this manner unless you have to attend to details, abstract ideas, or small words that can change the meaning of the text. It also causes difficulties when one has to perform on an important test or task. Even if a right-brain person gets the main idea of what they read they may end up struggling with final examinations, certification tests, qualifying tests, entrance examinations, or tests of reading abilities. They are placed at a disadvantage and low scores may mean anything from failure to low self-esteem, to not getting admitted into the school of their choice, and sadly, to dropping out. If a right-brain person's career depends on certification it could also affect his or her future. There are two options available to right-brain people who have to perform a left-brain reading task. One is to develop their left-brain skills. The second is to convert the task into a right-brain one so as to perform it well. Without this training, right-brain people may pass through a good portion of their lives needlessly struggling with reading, feeling like failures, and missing many opportunities to advance themselves and their career. 
<br><br>
<b><i>Spelling</b></i>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Spelling is another task that requires writing letters in order, a left-brain function. Again, those who are using the right side of the brain for spelling will often find themselves mixing up letters because the right brain does not work in sequential order. This means that they may be a good writer, but in school or job situations people will see their poor spelling and may disregard their writing abilities. 
<br><br>
<b><i>Grammar</b></i>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Poor grammar can reflect on one's writing abilities, speaking abilities, and educational background. A right-brained person could be brilliant, but if he or she does not speak or write in a grammatically correct manner others will not know the depth of his or her intelligence. Again, right-brain students struggle and find themselves getting low scores when it comes to tasks involving grammar even though they may have brilliant ideas, because grammar requires attention to details and sequential order.
<br><br>
<b><i>Writing</b></i>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Right-brain people may have great and creative ideas, but much of writing in schools and on the job is evaluated according to left-brain rules and criteria. Thus, organization and logical structure, writing ideas in sequence, correct sentence structure, and correct use of the mechanics of writing are left-brain functions.
<br><br>
<b><i>Foreign Languages</b></i>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Foreign language study requires success in reading, writing, spelling, speaking, and grammar. It also requires the storage of two languages in the brain. People who use the right side of the brain to learn a foreign language may find themselves struggling with certain tasks.
<br><br>
<b><i>Math</b></i>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Certain math tasks pose another problem for people who use the right side of the brain. Many math problems can be done with right-brain techniques. Right-brain people can grasp the whole picture, identifying a pattern, and see interconnections. But when the task is presented as a word problem or as a problem the reader must solve in a step-by-step method, right-brain people tend to struggle. Even when they can get the right answer for a problem they often do not get credit because they did not write down a detail. They are often penalized for being unable to explain, in words, how they arrived at an answer. 
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Sometimes people with a strong right-brain preference may transpose numbers. They know what number they are writing, but when they write, two numbers often come out transposed or totally backward. This happens because the right side of the brain sees the whole number simultaneously; it is the left side of the brain that puts the digits in order. When a right-brain person does not take the time to double-check a number it may come out mixed up. Thus, tasks involving accuracy of computation may suffer. 
<br><br>
<b><i>Jobs</b></i>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;There are many jobs that require attention to order and detail: computer programming, accounting, being a bank teller or a cashier, engineering, or proofreading, to name a few. People who have a mixed preference should be aware that they will have to use the left side of the brain to perform the tasks listed above. Right-brain adaptations are given in the book "How To Learn Anything Quickly" by Ricki Linkman.
<br><br>
<div style="text-align:center;"><b>Using the Left Side of the Brain for Right-Brain Tasks</b></div>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;When someone with a mixed preference has been in the habit of using the left side of the brain to perform right-brain tasks, they may struggle just as do those who use the right side of the brain when performing left-brain tasks. Here are some situations in which using the left brain may impede performance of a right-brain task. 
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;In offices or planning sessions, brainstorming is often a desirable way to generate ideas and solutions for problems. The session requires letting one's mind stay open to various possibilities. It is a time in which suggestions on the floor can trigger other associations and ideas. Someone with a mixed preference may end up engaging the left side of the brain and hindering the brainstorming session. Instead of staying open to all possible suggestions, the left-brainer will begin judging and analyzing each suggestion in a microscopic way, arguing why it would or would not work. The brainstorming session is not the time for judging and evaluating the details of each idea. Interrupting a brainstorming session -- a right-brain task -- can bog down the process and stop the free flow of ideas needed to find solutions. The left brain needs to reserve its analytical abilities for a later time, after the brainstorming is over, when the specific suggestions are looked at for their practicality. 
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;In tasks such as art, music, new product design, movie production, science and technology, or advertising, which involve creating or inventing something new, left-brain persons may have a hard time. They are stuck with the ideas and concepts they already know and cannot make the leap into the new and unknown. They would rather produce a step-by-step recipe than explore unknown territory. They would rather be told what to do or follow directions than have the freedom to create anything they want. They need to learn to develop the right side of the brain's simultaneous thinking to help them with new ideas, make new connections, and imagine new possibilities. They must adapt the right-brain task to the left side of the brain and use their own step-by-step approach to come up with new ideas, or develop the right side of their brain. 
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;There are many tasks that require the right side of the brain. People with mixed preferences may be using the left side for tasks that would be better serviced by the right side of the brain. They, too, need to know which side is appropriate for which task so they can use that side appropriately. Left-brain adaptations are given in the book "How To Learn Anything Quickly" by Ricki Linkman, which focuses on techniques for learning by using your best learning link. 
<br><br>
<div style="text-align:center;"><b>Mistaken Identity</b></div>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Many people grow up thinking they have a learning problem or a learning disability when in fact they are just using the wrong techniques to learn. Even today there are thousands of students who are classified as learning disabled when, in fact, a task is not presented in a way that is compatible with their brain hemispheric preference or they have not been taught how to use the side of the brain that matches the task. A learning disability is a "dysfunction of the central nervous system," which means there is impairment in the circuitry between the senses, the nervous system, and the brain. This impairment can be thought of as a short-circuit in the nervous system that scrambles a message as it travels from the senses to the brain and back to the senses. This situation does not apply to someone with a mixed preference who has no central nervous system dysfunction, but who has just not been taught how to use the right side of the brain for right-brain tasks and the left side for left-brain tasks. Someone with a mixed preference may make the same mistake as someone with a learning disability, but there is a world of difference. The learning disabled person has irreparable damage to the central nervous system. Thus, no matter how many times they do the same task they will not get it. They have to learn how to accomplish the task using different sensory modalities or techniques. But someone with mixed preferences can learn how to use the other side of their brain, or can convert the task to match the side of the brain for which they show a preference. It is not a question of damage, but of usage. They have been using one side of the brain since childhood and it has developed more neural connections, making that side more efficient and rapid. The other side of their brain can be developed also, or the task can be restructured to match the preferred side.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;There are many people with mixed-preferences who use each side of the brain inappropriately and grew up thinking there was something wrong with them. This may have affected their self-esteem and their motivation to succeed, and they may have actually dropped out of school or not continued on to higher education thinking there was something wrong with them. Only as an adult do many people with mixed preferences discover that they are not "dumb" or "stupid," but that the system they used failed them. They discover that when the instruction matches their learning style they are excellent learners. It is only the approach used during their school career that was wrong, and with a new approach they can finally feel success.
</div>
