<br><br>
<div style="page-break-before:always;">
<div class="crsLarge" style="text-align:center;">Tactile Left-Brain Learners</div>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tactile left-brain learners learn sequentially through the symbolic language of letters, numbers, and words. They also learn using their hands and fingers, their sense of touch, and their emotions. They often hold a pen or pencil and write to help them think and listen better. If they are told to put their pen away they will find some other object to touch.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;They are sensitive to language coupled with nonverbal communication such as a speaker's facial gestures, body language, tone of voice, and mood, which makes them doubly aware of other people's messages. They maintain eye contact mostly to read a speaker's expression and then look down and away when they think. They tend to be able to articulate their own feelings well and can easily empathize with others. They often gesticulate with their hands and are generally expressive. Tactile left-brain people are sensitive to other people's feelings and their own feelings get hurt easily. They think with their hearts and express their thoughts verbally or in writing in terms of feelings. If learning material is tied to a physical or emotional sensation it will be more meaningful to them. They spend time working out relationships, being with family and loved ones, writing letters, or talking on the telephone.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tactile left-brain people get new ideas as intuition or gut feelings and then conceive of the step-by-step approach for carrying them out. When ideas come, tactile left-brain people feel compelled to write them down sequentially. They may wake up in the middle of the night with an idea and have to write it immediately. They can be passionate about their ideas, and this enthusiasm rubs off on others. They are highly motivated and use their logic and ability to express their feelings in words that convince others of their ideas.
<br><br>
<div style="text-align:center;"><b>Accelerated Learning</b></div>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tactile left-brain people accelerate their learning by participating in activities that require the use of their hands and fingers. They need to write what they see and hear in order to learn in a sequential way. They are interested in words and numbers. In seminars or lectures they may take copious notes in a linear, sequential way, but will never need to look at them again. The act of writing, by itself, helps their brain process information. Many think and listen better when they doodle, draw, or hold something in their hands. Copying material from a text or taking dictation from a lecture enables them to recall the material later. They also recall the order in which they write notes. Because of their left hemispheric dominance they tend to organize notes or make outlines, lists, diagrams, or charts.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;For every subject they learn, they require active hands-on experiences with manipulatives to accompany a lecture or seminar. Once they have typed something, they will remember it. They learn by constructing and building things with their hands in a linear, step- by-step way. In science they need to not only perform an experiment (a good hands-on activity), but write about the results. They do not learn well if a teacher just shows and explains new material to them without allowing them to first write it down or guiding them in performing a task so they "get a feel" for doing it.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;In order to learn, tactile left-brain people need to use paper, notebooks, blank books, journals, diaries, stationery, pencils, pens, markers, crayons, paints, sculpting materials, arts and crafts, board games, computers, sports equipment that involves the hands, musical instruments, and other hands-on materials. Sequential computer programs that allow them to type, interact on an emotional level, and communicate with others are ideal.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;When memorizing material for a test, they will best recall the material they learned by touching, writing, drawing, or experiencing it on an emotional level. They can recall a subject in detail when they can associate the experience with a physical or emotional sensation while learning, and this makes it more meaningful and relevant to them. Visual and auditory details can be remembered if tied to an emotion. Thus, they will remember seeing a smile that conveys warm feelings and remember hearing words conveyed with love. When tactile children learn their language, it is the love of their parents expressed through words that helps the words sink in.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tactile left-brain people learn well in a peaceful environment, such as a setting in which they can see mountains, trees, or a lake. They need to be comfortable while studying. Many like to stretch out on the floor, recline comfortably on a chair, or lie on a couch. They may be able to type, write, read or study with music – if it is music they like, because they focus on feelings, not words. The good feelings their favorite music brings them help them tune out other negative stimuli, focus on positive feelings, and thus stimulate them to be more productive.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;They need positive feelings in order to concentrate or they may shut down. And they cannot concentrate when they feel others do not like them. Negative vibrations from others, both verbal and nonverbal, need to be minimized. If they feel emotionally uncomfortable, tactile left-brain people use language in an organized, clear way to question others about what they are really feeling based on their tones of voice, and will talk with others to straighten out the situation. If they cannot talk about their feelings, they can write them as poetry, essays, or journal entries.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tactile people can benefit from learning in cooperative teams or groups. They thrive on positive feelings from group members with whom they feel comfortable, and whose appreciative words and warm touches help them work better. If their socializing distracts others, tactile left-brain people can be encouraged instead to write to their friends in class. Socializing with others does not hinder their ability to listen and work, but actually increases their interest in their work.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;To accelerate reading, tactile left-brain people need to internalize what is happening. They need to feel what the words describe and what the characters are feeling. They are bored if they cannot emotionally identify with the reading material. If they are reading about abstract subjects they should try to feel what is happening. For example, if they are reading about a chemical reaction, they need to become one of the chemicals and experience rising up as a gas themselves. If they are reading a biography, they need to feel what the person would have lived through on a physical and emotional level. They can actually recall everything they read if they convert it into a feeling. What they do not convert into a feeling can be lost.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;In whatever they read, they will also remember it better if they jot down their ideas as they read. They may read books or novels that have depth, feeling, and a powerful message. They may read self-help and how-to books to solve a problem, to help them deal with feelings and relationships, or to learn something important for their jobs or life skills. They prefer it if these topics were written in a step-by-step, logical way.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;In the workforce, you may find them in jobs that require the use of their hands and fingers, or emotions that involve working in a step-by-step way. They tend to be structured and organized in their work. If they go into the fine arts, they approach the work in a detailed way. When they draw they tend to be good at copying what they see in detail and paying more attention to the technical aspects of the art. They may enter the commercial arts and do layout, design, fashion illustration, children's book illustrations, or advertising.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Some play instruments or write music and songs because these activities involve both their hands and fingers and their feelings. Over their careers, they reach others' hearts by involving their feelings and touching them in a deep way.
<br><br>
<div style="text-align:center;"><b>Adapting Learning to a Tactile Left-Brain Style</b></div>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tactile left-brain people should ask an instructor to let them take notes from a lecture or seminar or from printed outlines, study guides, or data presented in sequential order. For taking sequential notes on their own, they need sequentially organized books and other written or audio-visual materials. They can talk to an instructor or coworkers about their need for positive communication and feedback. If there is no change in a negative environment, they can write their thoughts and feelings in a journal or talk to someone. They can also learn relaxation techniques and coping skills to deal with their sensitive feelings.
</div>
