<br><br>
<div style="page-break-before:always;">
<div class="crsLarge" style="text-align:center;">Tactile Right-Brain Learners</div>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tactile right-brain learners are sensitive people who tend to think globally. They look at the big picture or overview, and they learn using their hands and fingers, their sense of touch, and their emotions. They use intuition, imagination, language that expresses feelings, and sensory words. They are adept at reading nonverbal communication and also express themselves in a nonverbal way by making faces or sounds of pleasure and displeasure, or by gesticulating. They are sensitive to others' feelings and their own are easily hurt. They are moved by sad or touching parts of movies and books.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Loving relationships are important to them because they need to "feel good" emotionally to function. They spend a great deal of time communicating, either on the phone or face to face so they can read other people's nonverbal expressions and tones of voice. They maintain eye contact mostly to read others' expressions and will look down and away to think.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tactile right-brain people think with their hearts. They get new ideas and information intuitively. They feel passionately about these ideas and can be very persuasive when relaying their ideas to others. They may not be detailed or systematic in bringing the idea into reality but often jump in and do it impulsively. They have the end product in mind and will try to get there as quickly as possible without worrying about details.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Since they do not need to think in terms of words, but only ideas, they can understand new information quickly because they can comprehend the whole picture instantaneously. They often startle those around them by accurately guessing what the other person is thinking. They can get the gist of a two-hour lecture in moments through intuition.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;They work in an original and imaginative way. They often come up with new images and designs that no one has thought of before. As writers, they gravitate to imaginative kinds of writing. In the arts, they create new art forms or new ways of presenting old forms. They use art to express their feelings. They may be involved with arts and crafts, sewing, knitting, textiles, pottery, basket-weaving, jewelry-making, or woodworking. Some like to play an instrument and create their own original and imaginative music and songs. They can play by ear and pick out a tune without reading music.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Some tactile right-brain people enjoy games and sports that involve their hands. Since they do not have the patience for the constraint of organized games with long directions, rules, and regulations, they prefer to play for fun. They do not necessarily play to win, but for the social contact with people they like, or because they like the feel of the game. When learning these games they tend to just jump in and perform, getting a feel for them as they go along and learning by trial and error. Many prefer free-form games and sports in which they can be creative in their moves, such as dance, gymnastics, ice skating, roller skating or rollerblading, or swimming.
<br><br>
<div style="text-align:center;"><b>Accelerated Learning</b></div>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tactile right-brain people can accelerate their learning by involving their hands, fingers, and feelings. Since they are not attuned to symbolic language, they learn through sensory language or nonverbal communication that gives the big picture. They learn by sketching and drawing pictures, diagrams, illustrations, maps, and making sculptures, models, or artistic booklets of what they hear and learn.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;They may take notes by drawing but never need to look at them again. They remember new material better when they take notes using calligraphy or colorful, artistically-drawn letters. The act of drawing or writing artistically helps them understand and remember the material. When listening to seminars, talking on the phone, or speaking to someone they may doodle or jot down quick sketchy notes, pictorial icons, diagrams, or mind maps in a way that shows the relationships between the points. Since they are not auditorially attuned to abstract language, it helps if they can see visuals or graphics they can copy.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;To listen or think better, they need to do or hold something with their hands. It could be a pen, paintbrush, clay, a computer mouse, or any object. If they are told not to touch anything they will fidget, play with objects, tap their fingers on their desk, or play with their hair.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;They also need the big picture, not the small details, or they will be lost. They may become impatient with lengthy written directions, and would rather just try to get a feel for the project at hand. When learning how to do a math problem they need to see the whole problem with the answer and all the steps mapped out. They should then try to do it themselves. The right side of the brain is adept at figuring out mathematical patterns just from seeing the problem and its solution and similar examples several times. When memorizing material for a test, they recall what they felt, touched, drew, or wrote. The subject needs to be tied to their physical or emotional responses.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tactile right-brain people need hands-on experiences and manipulatives to learn. Lecturing or reading directions will not be as effective unless their hands can be involved. Writing and illustrating the table of elements help them remember it. Hitting the key strokes helps them learn a software program.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;If it is not possible to use their hands, they need to use their imagination to visualize themselves doing a task with their hands and feeling the sensation in their mind. Tactile right-brain people need the following learning materials: sketch pads, drawing paper, notebooks, blank books, diaries, pencils, pens, markers, crayons, paints, sculpting materials, and arts and crafts materials. In math, using objects, calculators, or manipulatives helps them learn faster. Real-life items, such as tools and equipment from all fields, board games, sports equipment, or musical instruments can help them learn many subjects. They like the more free-flowing, non-sequential aspect of the computer offered by the use of the mouse, or user-friendly programs that require a click on an icon. Their tactile dexterity can also make them quick at typing. They may also learn about graphics to create computer art or layouts in desktop publishing programs.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;They learn best in a positive learning environment that is physically and emotionally comfortable. Negative nonverbal communications from others need to be eliminated. Due to their sensitivity to nonverbal communication their right brain picks up sarcastic tones, resentment, hatred, annoyance, and other negative feelings. When they hear these tones, their openness to learning shuts down. They may withdraw or respond nonverbally, expressing resentment through defiant looks, resistant body language, and negative tones of voice. Their attentiveness increases when they are not distracted by the negative feelings of others.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Coaches or instructors can help them refine their technique if they offer help in a positive way when asked, but they need to be careful that the tactile right-brain person does not perceive any negative tones or they will turn off to them. It is better to wait until the tactile right-brain person asks for advice first before offering it, lest it be taken the wrong way.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tactile right-brain people like to work in a peaceful environment or a natural setting. They need to be comfortable while studying, and will stretch out on the floor or in a chair, or lie on the couch. They can learn with or without music, but it has to be music they like or they will be disturbed. They are not distracted by music when they read or study because they do not focus on words; they get a holistic impression of the music, its message and mood from the tune and the words, and pick up positive feelings. Some enjoy music that combines the sounds of nature with pleasant music. Music has a calming, relaxing influence, minimizes sad and negative feelings, lifts their spirits, and increases their ability to learn.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Working in cooperative teams or with one or two people they enjoy can increase their ability to learn because they thrive on the positive feelings from others. Praise, appreciation, and positive nonverbal expression accelerate their learning.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;To accelerate reading, tactile right-brain people need to feel the written message or identify on an emotional level with the subject or character. They can thumb through a book, open a page, and find whatever information they need without reading all of it. They will often skip over details and lengthy explanations to get to the bottom line.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;They like books that touch their emotions and become bored if they cannot relate to the emotional interaction between characters. When reading about abstract subjects they may personify the material to make it come alive.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Books that are rich in imagination and have depth, feeling, or a powerful message appeal to them. They like how-to and self-help books dealing with feelings and relationships. After reading, they remember the text if they make sketches, drawings, or iconic symbols as they go along. They take notes by writing key words, preferably in color or with an artistic design. Writing their notes in a pictorial or diagram form, such as a mind map, helps them remember them better.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;In the workforce they may be writers, artists, photographers, film-makers, or musicians. They may work in engineering, architecture, city planning, technical writing, designing electronic and technical equipment, drafting, electrical work, construction, building, farming, gardening, landscaping, floral arrangement, painting, plumbing, wallpapering, cooking, the restaurant business, or any field involving their hands. They can find easier, more efficient, and more creative ways of doing these jobs and will look at them through paradigms that no one had thought of before.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Some may be involved with film-making, photography, dancing, or acting, often looking at life in new ways. If they go into acting they are good at portraying the feelings of other people. Their sensitivity to other people's feelings may involve them in professions that allow them to alleviate others' suffering or help people, such as social work, psychology, therapy, education, medicine, health, humanitarian projects, or peace movements.
<br><br>
<div style="text-align:center;"><b>Adapting Learning to a Tactile Right-Brain Style</b></div>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tactile left-brain people should ask an instructor to provide the big picture using short, sensory language. They should be allowed to draw, do hands-on projects, or make a mind map in a global, creative, free-flowing way. Since it is hard for them to follow auditory presentations, they need a written copy of notes or readings complete with illustrations. They should convert each word at their own pace into a mental movie, colorful, artistic, and creative drawings, mind maps showing the main topic and details and their interconnections, hands-on projects, or decorative and colorfully written words, calligraphy, or designs. They need to observe real-life demonstrations and draw a mind map that gives the big picture.
</div>
