<br><br>
<div style="page-break-before:always;">
<div class="crsLarge" style="text-align:center;">Visual Left-Brain Learners</div>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Visual left-brain learners take in visual information and convert it into symbols or language, such as letters, numbers, words, or ideas. Although they are sensitive to their visual environment, they pay particular attention to printed matter – letters, words, or numbers. They label this sensory information with names and words. They think in a step-by-step way, attending to one detail at a time, and file data in a systematic way, either alphabetically, numerically, or chronologically.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Since they like to stay organized, they are often engaged in organizing materials involving words and numbers. They may spend time filing their papers, organizing phone numbers and addresses, keeping their finances up to date, paying bills, doing budgets, scheduling appointments in their offices or homes, keeping up with correspondence, programming their computers, doing spreadsheets, or making sure birthday and anniversary cards are mailed out on time. They may find organized and efficient ways for setting up accounting, payroll, record-keeping, or bookkeeping systems.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;To keep their affairs in order they may make charts and graphs. They are good at keeping company records, archiving, setting appointments, making chronologies and timelines, keeping timetables, scheduling, and other such tasks. They do not miss a detail and seldom miss an appointment, as long as it is written down so they can see it.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;When they are traveling, they plan everything they are going to see in detail in advance. They collect travel brochures, schedules, and information and make reservations far in advance. They like to stick to their planned schedules and feel uncomfortable when anything interferes with the trips they have already visualized and planned in their minds.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;When visual left-brain people think, their eyes tend to look upward towards the ceiling, either upper left or upper right, because they process their thoughts by seeing words or images. Everyone's eyes do this when we picture something mentally, except that visual left-brain people are in that mode more often. Visual left-brain people maintain eye contact with a speaker to help them "listen" better. They will turn in their chairs to follow a speaker around the room with their eyes. Visual left-brain people also need those who are listening to them to give them eye contact as well. They become disturbed when they talk to someone who looks down and away, and will sometimes even say, "Look at me when I am talking to you." They need to understand that the eyes of people having other learning styles move in different directions. Eye movements correspond to the modality in which our brain is processing. Although people who have other learning styles do not maintain steady eye contact with a speaker, it does not mean they are not listening; rather, they listen <i>better</i> when their eyes are not continually on the speaker.
<br><br>
<div style="text-align:center;"><b>Accelerated Learning</b></div>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Visual left-brain people accelerate their learning by reading and seeing visual materials in the form of language: letters, words, and numbers. They also need eye contact with a speaker. They learn any subject more quickly through reading books and study guides if the information is organized and clearly written in step-by-step order. To learn a language they need to see a vocabulary word, its definition, and visual clues for its pronunciation. To learn math they need to read step-by-step instructions showing them how to do a problem. They tend to be accurate with mathematical calculations. Self-study programs that require reading are excellent for them.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;They learn through print materials such as books, magazines, journals, newspapers, technical manuals, guidebooks, instruction books, computers, film strips and overheads with words to be read, videos with captions, faxes, tables, graphs, charts, and posters. Written communication is the best way to get a message across to them. They are quicker at responding to faxes, e-mail, written directions, memos, or letters than to phone calls or verbal communications. Computer programs and electronic communication networks that require reading texts with step-by-step detailed instructions are ideal for visual left-brain people.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Visual left-brain people can study with or without music. Music, noise, or talking does not bother them because they are visually attuned and are not paying attention to the auditory stimuli around them.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Due to their keen sensitivity to visual stimuli they are bothered by visual clutter or disorganization in print material. They recall what they have seen and can spot whether print looks right to them: It is as if they have an automatic spell-checker in their brains. They make excellent proofreaders and copyeditors. They can also spot errors in numerical information such as financial reports, budgets, paychecks, tax returns, restaurant checks, or spreadsheets. These are the people who will take a red pen to circle other people's errors. (It must have been a visual left-brain person who invented proofreader's markings!)
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;They can learn and remember the rules of writing, grammar, punctuation, and spelling if the material is presented in order with rules and formulas printed out, and they can visually recall the examples they see in a textbook. They need everything in their visual environment to look right, especially printed material.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;How-to and step-by-step books and guides written in a clear, sequential manner accelerate the visual left-brain person's learning. They can learn how to build a motor, cook a meal, build an addition to a home, or run a business by reading about it rather than merely observing it.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;When working on projects or solving problems, visual left-brain people should outline or sequentially list the steps they need to do to reach solutions so they can see their plan on paper, and make sure they have everything they need to carry out each part of the task. Visual left-brain people make excellent administrators and managers because they are extremely organized and can see a task through to completion.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Visual left-brain people like to learn according to a schedule and deadlines. Keeping an organizer, calendar, or day-timer is ideal for them so they can see their schedule.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;To accelerate reading, visual left-brain people must visualize the words and details they read. Since reading words is a visual, sequential, and symbolic activity, they already find reading easy. As they read, they visually record every word in order and can recall the material when questioned. Thus, they tend to do well on tests on memorization of reading material. These people are good test-takers if they have study guides, notes, or textbooks from which to study. Some of them are like walking encyclopedias. Ask them to find a fact and they will not only recall what book they read it in, but where in the book they saw it and what visual material surrounded what they read. They are good at skimming to find needed data.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;In the workforce, dealing with print material, either in words or in numbers, is ideal for them. In the world of words they can be found in: administration, management, office work such as preparing reports, filing, secretarial work, scheduling, appointment setting, areas dealing with time-management and efficiency, publishing, writing, editing, word processing, desktop publishing, proofreading, teaching, research in any field, library work, writing copy for advertising, marketing, sales, and writing technical and instructional manuals, reviews and literary criticism. In the world of numbers they can be found in accounting, business, finance, stock brokerage, tax specialization, banking, budgeting, economics, financial planning, insurance, payroll, mathematics, statistics, evaluation and measurement, market research, and computer programming.
<br><br>
<div style="text-align:center;"><b>Adapting Learning to a Visual Left-Brain Style</b></div>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Because visual left-brain people focus well on details, their learning is slowed down when they have to condense or summarize the gist of what they read to get the main idea. Thus, they do better on recall of facts they read, than on getting the big picture or making inferences, since these are unstated and they have not <i>seen</i> them written in the text.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;They should ask instructors for visual material such as outlines, study guides, or notes in sequential order on a board or paper to help them see what is important. In this way they can see it, read along, or ask questions to organize the information in their mind. They can make their own notes by writing themselves or taking dictation in a sequential organized way, such as outlining or making a graphic organizer, so they can see the material in their mind. They may need to find their own sequentially written books and materials that correspond with the subject in order to learn it on their own. 
</div>
