<br><br>
<div style="page-break-before:always;">
<div class="crsLarge" style="text-align:center;">Visual Right-Brain Learners</div>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Visual right-brain learners take in information through their eyes and are attuned to images, pictures, graphics, colors, shapes, designs, sizes, and spatial relations. They process and think about these stimuli in a simultaneous way, seeing the whole picture at once. Only after they grasp the big picture can they focus on its details.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;They are attuned to the way things look and are bothered by visual clutter. They notice when the colors in a room do not match or if an object is out of place. They make good interior decorators, and with their keen sense of visual balance and design they have a good eye for what accessories go together in a room and can rearrange one until it looks visually pleasing. This same sensitivity makes them notice how people look and dress. They like clothes that look good and use their great eye for color and design to select matching clothes and accessories. They enjoy having their own clothes, skin, hair, or face look good as well as making others look good. Some may tell others when their hair is out of place, their tie does not match their suit, or a button is open. They are so keenly aware of how things look they can become distracted unless the disturbing visual appearance is fixed.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;They like to produce work that looks visually appealing in design and color. These are the people to whom others come for attractive presentation packets, color photocopies, attractively bound reports, and visual aids. Visual right-brain learners are the ones who beautify the world. They will hang paintings in a room, keep attractive posters around the office, and bring in flower arrangements. People call on them to decorate the office for the staff party.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;They may like going to art galleries, photo exhibits, fashion shows, auto shows, or sightseeing. They may get pleasure from looking at beautiful homes, gardens, cars, boats, horse or animal shows –- anything that can be seen. They may enjoy the visuals of the theater, a circus, a museum, a zoo, a park, gardens, or amusement parks with fascinating sights to see. 
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;While they do not keep their things in an organized, linear way like their left-brain counterparts do, they want their visual surroundings to be appealing and will find a way to keep their things in an attractive way. Although they may not be filers, they will have attractive organizers such as colorful boxes, stylish containers, decorative pencil holders, and storage units for their belongings.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Since visual right-brain people think and remember mostly in images, their eyes tend to look upward toward the ceiling, either upper left or upper right. When they are listening they maintain good eye contact and are often watching the movements of the speaker's mouth as well as facial expressions. Visual right-brain people also need their listeners to look at them when they talk and will even request others to do so.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Visual right-brain people go with the flow and end up being in the flow, often becoming so absorbed in their projects that they lose track of time. Since time awareness is not in the right side of the brain, they start and finish work on their own time according to the demands of the project rather than the clock.
<br><br>
<div style="text-align:center;"><b>Accelerated Learning</b></div>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The best way for visual right-brain people to learn is through visual aids with graphic and pictorial content that allow them to see the big picture. They do not learn from or remember texts or numbers as well unless they are presented using color, shape, design, special calligraphy, or an artistic font.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Many visual right-brainers do not respond to verbal instructions and will do nothing until given visual directions on paper with pictorial images, diagrams, or charts. Pure lecture does not work because they have to work hard at concentrating on auditory stimuli. When they can see a speaker, graphics, and visual aids, their best learning modality is open and whatever talking comes in, coupled with the visual stimuli, will be received and recalled. They learn and remember better by having eye contact with a speaker rather than listening to an audiotape lecture, but the speaker must also give them something to look at in pictorial form. If they do not have anything to look at, they should listen to the descriptive words in a lecture so they can paint a mental picture for themselves. They will have a hard time understanding what others are saying unless they are provided with descriptions of color, size, or shape to visualize. 
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;They need to see books, magazines, and overheads with illustrations, pictures, drawings, paintings, or photographs and slides, videos, and movies with people and beautiful, visual, and scenic imagery so they can see what you are talking about. Seeing live examples, real-life objects, demonstrations, enactments, videos, movies, television, slides, or photographs are other stimuli that help them understand and learn. They like computer programs with good graphics and visual images that operate using icons and pictorial directions, rather than detailed, sequential directions.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Visual right-brain people can work with or without music. Music, noise, and talking do not distract them because they are more focused on what they are seeing than what they are hearing.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;When describing events or experiences from the past, visual right-brain people will recall images they saw in real life, movies, photographs, and videos, the surroundings, and what people looked like. They are great at spotting famous personalities and people they know in different contexts by matching visual features.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;It is easier for them to do math problems when there is a photograph or a pictorial image to accompany the problem as an example. If they are multiplying 24 by 3, they want to see a picture of twenty-four people each holding three slices of pizza.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Using intuition, experimentation, and discovery, they can uncover new ways to do things and find solutions to problems. They make associations easily and one image will bring others to mind. This makes them good at learning through brainstorming or making connections. Since they think things through in a simultaneous way, before starting a project, they first need to know the end product, goal, or bottom line. Once they see the big picture the connections between every part make sense to them. After they get the big picture they are impatient with step-by-step directions and want to jump in and figure it out for themselves as they do it.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Visual right-brain people can accelerate their reading by converting a text into images so they can see what they are reading in their head. This dramatically improves their comprehension. It is hard for the visual right-brain person to grasp words that do not invoke images, such as articles like <i>a</i> and <i>the</i>, verb tenses, or prepositions. Many tend to focus on words that can be pictured and skip over these small abstract words that cannot be pictured, like <i>the</i>, <i>that</i>, or <i>and</i>, or they substitute <i>the</i> for <i>a</i>, and vice versa. Thus, on a test, they score higher on questions that contain visual imagery and lower on those that cannot be visualized. If they need to pass an examination or master abstract material, they need to develop the right-brain technique for visualizing everything, even abstract words.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;In the workforce, you will find visual right-brain people engaged in the fine arts and graphic design. With their expert eye they may be artists, illustrators, painters, sculptors, jewelry makers, clothing designers, fashion illustrators, interior decorators, beauticians, cosmetologists, or hairdressers. They may be involved in graphic arts, commercial illustration, advertising, or designing posters, brochures, sales pieces, or billboards. In the publishing world they may be art directors, children's book illustrators, the layout and design people, and those that make "beautiful" books. They make good photographers, and you will find their work beautifying magazines, books, brochures, booklets, and other print media. Other activities they may enjoy are floral arranging, landscaping, or architecture. They want their visual surroundings to be beautiful. They may be the ones to design stationery, greeting cards, or new forms of calligraphy or typography fonts. As engineers they want to design buildings, structures, or transportation vehicles that look good. They make good car designers, coming up with new sleek, beautiful models.
<br><br>
<div style="text-align:center;"><b>Adapting Learning to a Visual Right-Brain Style</b></div>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Visual right-brain learners need to ask instructors to provide visual images showing the global overview. They need to see the big picture using pictorial images, mind maps, real-life objects or demonstrations, or find their own materials. Since auditory presentations are difficult, they need to see a written copy of a lecture or write their own so they can read at their own pace, converting each word into a mental image; a colorful illustration; a mind map of the main topic, the details, and their interconnections; or words and numbers written in colorful, decorative calligraphy or design so they can "see" the material.
</div>
