<br>
<hr width="90%" style="text-align:center;">
<br>
<div class="crsSmall" style="page-break-before:always;margin-left:50px;margin-right:50px;">
<div class="crsMedium" style="font-weight:bold;text-decoration:underline;">Admission Likelihood</div>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The Admission Likelihood is NOT in any way a guarantee of admission by any college or university. Rather, the Admission Likelihood (Safety, Target, Possible, Reach, and Far Reach) is intended to be a gauge of a student's likelihood of admission at a given college or university as derived from College & Retirement Solutions' proprietary formula, comparing the academic profile of the college's admitted freshmen class from the previous year and the student's GPA and standardized test scores. Because there are many factors that influence a student's overall likelihood of admission, standardized test scores and GPA are the most tangible and dependable indicators of admissibility. Most students have individual characteristics and qualities working for them that can increase their chances of admission. Although these are vital in determining admissibility at a college, there is no way that this individuality (leadership, sports, extracurricular activities, etc.) can be assessed in this formula.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Therefore, <img src="../images/CollegeChoiceLogoSmall.gif" width="73" height="18"> is a guide only and should not be considered in any other way. Students may choose to apply wherever they have an interest in attending even if the probability of being admitted is unlikely. College admissions trends and policies often reflect institutional priorities which can mean that a student's admissibility could easily change from year to year. Keep in mind that some schools are so selective that they have become a Far Reach for virtually every candidate, regardless of academic strengths, merit, or status as a legacy applicant.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Test scores and GPA are the lowest common denominators of admissibility; they are not the student's whole <i>entrance</i> story. These factors are too numerous, far ranging, and subjective to include in the scope of this report, especially since college admission policies vary so widely from year to year. These subjective factors must be considered on an individual student and college basis, respectively.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="../images/CollegeChoiceLogoSmall.gif" width="73" height="18"> was created to identify to a student which school they have a real chance at getting into and what kind of cost will it likely be.
<br><br><br>
<div class="crsMedium" style="font-weight:bold;text-decoration:underline;">EFC</div>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The calculation of Expected Family Contribution (EFC) in this <img src="../images/CollegeChoiceLogoSmall.gif" width="73" height="18"> report is an estimate based on the Federal Needs Formula (FM) and the Institutional Needs Formula (IM) and is not a guarantee of your actual EFC. <img src="../images/CollegeChoiceLogoSmall.gif" width="73" height="18"> is taking a streamlined approach in calculating your Federal and Institutional EFC and is requesting less information than what is otherwise required for the financial aid forms. Although streamlined, this approach towards the EFC calculation still generates an accurate EFC for most families. However, if you itemize deductions on your tax returns, make generous contributions to qualified retirement plans, or are self-employed, then your EFC may vary from the <img src="../images/CollegeChoiceLogoSmall.gif" width="73" height="18"> calculation.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;It is important to note that <img src="../images/CollegeChoiceLogoSmall.gif" width="73" height="18"> is updated on a regular basis. The EFC that has been calculated is the EFC of the student for whom you have reported income and asset information. If there are additional students in college at the same time, the additional student(s) will have an EFC of their own. Calculation of EFC changes from year to year based on the income and assets of students and parents, financial aid laws, and updated tax laws.
<br><br><br>
<div class="crsMedium" style="font-weight:bold;text-decoration:underline;">Financial Need</div>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Financial need is based on a simple formula which is determined by subtracting your Expected Family Contribution (EFC) from the college's Cost of Attendance (COA - EFC = Need). Depending on the cost of a school, you could have "need" at one school but not at another.
<br><br><br>
<div class="crsMedium" style="font-weight:bold;text-decoration:underline;">Percent of Need Met</div>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;This is the average percentage of financial need that is met by a particular college.  This statistical data is routinely reported each year by individual schools. <img src="../images/CollegeChoiceLogoSmall.gif" width="73" height="18"> will use this reported data to help identify what a potential aid package may look like. A student may be awarded based on demonstrated financial need and this financial aid package may be comprised of aid from various sources, such as state aid, federal aid, and the aid from the college itself.
<br><br><br>
<div class="crsMedium" style="font-weight:bold;text-decoration:underline;">Total Projected Aid (Need- and Merit-Based)</div>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="../images/CollegeChoiceLogoSmall.gif" width="73" height="18"> calculates projected aid in two forms. The first is based on need. The total projected aid (need) is derived by multiplying the need by the percentage of need met. The percentage of need met is an average for all students receiving aid at a given college, thus the actual amount of aid you receive, if any, may be substantially higher or lower than the total projected aid shown in this report. The second way <img src="../images/CollegeChoiceLogoSmall.gif" width="73" height="18"> calculates aid is based on merit, which is determined using the admissibility factors of the student, which yields an estimated percentile. The higher the percentile for that student, the higher the amount of merit aid offered to that student.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The total projected aid package listed in <img src="../images/CollegeChoiceLogoSmall.gif" width="73" height="18"> represents all forms of aid, and could include federal aid in the form of a Pell grant or Stafford student loan, if eligible. This statistical information has been reported by individual schools and is an estimate of the amount of federal aid (Pell grant and Stafford loan) that the student may be eligible to receive (an estimate only, not guaranteed in any way). This estimate of aid is in <u>NO WAY</u> a guarantee of what the student's aid award would consist of in terms of loans, grants, work-study, or scholarships from that college. In most cases predicting the makeup of a student's overall aid award at any college is nearly impossible since financial aid packaging policies vary among colleges and are influenced by a variety of factors each year. The only types of aid that can be predicted with any amount of consistency are some forms of federal aid and merit aid award programs published by individual colleges.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Merit aid is typically awarded on the basis of a student's academic merit. Thus, merit aid has nothing to do with a student's and parents' ability to pay. Even if a student doesn't qualify for need-based financial aid at a given college, the student may still qualify for merit aid that can reduce the overall cost.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The merit aid awards can be used as a strategy to compel a particular college to offer the student more than they may have. This is done by receiving a better offer from a comparable school. The schools that are listed in the comparable section are intended to offer some ideas of what the "interested" school demographic competes against.
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Merit aid scholarships are highly sought after by qualified students and many colleges publish such scholarships on their websites. However, these scholarships can change from one incoming class to another as a college's aid policy changes. Consequently, even the most diligent database sources of these scholarships are not always accurate and complete. The best way to search for merit aid scholarships is simply to visit each of the college's web sites included in this report, look for the financial aid area of the college's website, and contact the financial aid office directly.
<br><br><br>
<div class="crsMedium" style="font-weight:bold;text-decoration:underline;">College Data</div>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;College Data Source: Collegeboard, Copyright 2009-2010. Not all information may be available for all schools. The financial data in these estimates is based on information from prior school years and is intended for use only as a planning guide. For the most recent financial information, please contact your school's Financial Aid or Admissions Offices.
</div>